export const SEARCH = 'SEARCH';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const GET_EVENTS = 'GET_EVENTS';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';
export const GET_EVENT_DETAILS = 'GET_EVENT_DETAILS';
export const CLEAR_EVENT_DETAILS = 'CLEAR_EVENT_DETAILS';
